import { AdminActionButton } from "@/components/marketplace/admin-action-button"
import { FoundingClaimForm } from "@/components/marketplace/founding-claim-form"
import { loginAdmin } from "@/app/admin/actions"
import { formatMoney } from "@/lib/marketplace/helpers"
import { isAdminAuthenticated } from "@/lib/marketplace/admin-auth"
import { getAdminMarketplaceData } from "@/lib/marketplace/queries"

export const dynamic = "force-dynamic"
export const metadata = { title: "Admin", robots: { index: false, follow: false } }
export default async function AdminPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const query = await searchParams
  if (!await isAdminAuthenticated()) return <main className="grid min-h-screen place-items-center bg-[#f4f1ea] p-5"><form action={loginAdmin} className="w-full max-w-sm rounded-3xl border border-black/10 bg-white p-7"><p className="font-[var(--font-clash)] text-3xl">FIXTHIS admin</p><input name="password" type="password" required autoFocus placeholder="Admin password" className="mt-6 min-h-12 w-full rounded-xl border border-black/15 px-3" />{query.error && <p className="mt-2 text-sm text-red-700">Wrong password.</p>}<button className="mt-4 min-h-11 w-full rounded-xl bg-black text-sm font-bold text-white">ENTER</button></form></main>
  const { problems, placements } = await getAdminMarketplaceData()
  return <main className="min-h-screen bg-[#f4f1ea] px-5 py-10"><div className="mx-auto max-w-7xl"><h1 className="font-[var(--font-clash)] text-5xl tracking-[-.05em]">Market operations.</h1><p className="mt-2 text-sm text-black/50">Moderation, founding inventory, placements, and honest traffic.</p><section className="mt-10"><h2 className="font-[var(--font-clash)] text-2xl">Add founding claim</h2><div className="mt-4"><FoundingClaimForm problems={problems.filter((p) => p.status === "published").map((p) => ({ id: p.id, statement: p.statement }))} /></div></section><section className="mt-12"><h2 className="font-[var(--font-clash)] text-2xl">Problems · {problems.length}</h2><div className="mt-4 overflow-x-auto rounded-2xl border border-black/10 bg-white"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-black/5"><tr>{["Problem","Origin","Demand","Traffic","Status","Actions"].map((x) => <th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{problems.map((p) => <tr key={p.id} className="border-t border-black/10"><td className="max-w-md p-3 font-semibold">{p.statement}</td><td className="p-3">{p.origin}</td><td className="p-3">{p.support_count}</td><td className="p-3">{p.impression_count} / {p.click_count}</td><td className="p-3">{p.status}</td><td className="flex gap-2 p-3">{p.status === "published" ? <AdminActionButton entity="problem" id={p.id} action="hide" /> : <AdminActionButton entity="problem" id={p.id} action="publish" />}</td></tr>)}</tbody></table></div></section><section className="mt-12"><h2 className="font-[var(--font-clash)] text-2xl">Placements · {placements.length}</h2><div className="mt-4 overflow-x-auto rounded-2xl border border-black/10 bg-white"><table className="w-full min-w-[1000px] text-left text-xs"><thead className="bg-black/5"><tr>{["Product","Problem","Rank / bid","Traffic","Owner","Status","Actions"].map((x) => <th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{placements.map((p) => <tr key={p.placement_id} className="border-t border-black/10"><td className="p-3 font-semibold">{p.product_name}</td><td className="max-w-sm p-3">{p.problem_statement}</td><td className="p-3">#{p.rank} · {p.founding_claim ? "$0 founding" : formatMoney(p.current_bid_cents)}</td><td className="p-3">{p.impression_count} / {p.click_count}</td><td className="p-3">{p.owner_email}</td><td className="p-3">{p.status}</td><td className="flex gap-2 p-3">{p.status === "active" ? <AdminActionButton entity="placement" id={p.placement_id} action="suspend" /> : <AdminActionButton entity="placement" id={p.placement_id} action="restore" />}</td></tr>)}</tbody></table></div></section></div></main>
}
