"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"

export function FoundingClaimForm({ problems }: { problems: Array<{ id: string; statement: string }> }) {
  const [error, setError] = useState(""), [loading, setLoading] = useState(false); const router = useRouter()
  return <form className="grid gap-3 rounded-2xl border border-black/10 bg-white p-5 md:grid-cols-2" onSubmit={async (event) => { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/admin/founding-claims", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const result = await response.json().catch(() => ({})); setLoading(false); if (!response.ok) setError(result.error || "Could not create claim."); else { (event.currentTarget as HTMLFormElement).reset(); router.refresh() } }}><select name="problemId" required className="min-h-11 rounded-xl border border-black/10 px-3 md:col-span-2"><option value="">Choose a problem</option>{problems.map((problem) => <option key={problem.id} value={problem.id}>{problem.statement}</option>)}</select><input name="productName" required maxLength={80} placeholder="Product name" className="min-h-11 rounded-xl border border-black/10 px-3" /><input name="email" required type="email" placeholder="Founder email" className="min-h-11 rounded-xl border border-black/10 px-3" /><input name="destinationUrl" required type="url" placeholder="https://product.com" className="min-h-11 rounded-xl border border-black/10 px-3 md:col-span-2" /><input name="productTagline" required maxLength={180} placeholder="One-sentence problem fit" className="min-h-11 rounded-xl border border-black/10 px-3 md:col-span-2" />{error && <p className="text-sm text-red-700 md:col-span-2">{error}</p>}<button disabled={loading} className="min-h-11 rounded-xl bg-black text-xs font-bold text-white md:col-span-2">{loading ? "CREATING…" : "CREATE HONEST $0 FOUNDING CLAIM"}</button></form>
}
